using Singularity.Crash;

void test_report_parsing() {
    string data = "[Crash]\nSource=handler\nPid=4242\nUid=1000\nSignal=11\nTime=1790000000\n"
        + "Executable=/usr/bin/crashy\nCommandLine=/usr/bin/crashy --now\n"
        + "DesktopFile=/usr/share/applications/org.example.Crashy.desktop\nCore=1790000000-4242.core\n";
    var report = Report.from_keyfile_data(data, "/var/lib/singularity/crashes/1000/1790000000-4242.crash");
    assert(report != null);
    assert(report.pid == 4242);
    assert(report.uid == 1000);
    assert(report.signal_number == 11);
    assert(report.timestamp == 1790000000);
    assert(report.executable == "/usr/bin/crashy");
    assert(report.app_id == "org.example.Crashy");
    assert(report.core_path == "/var/lib/singularity/crashes/1000/1790000000-4242.core");
    assert(report.source == SourceKind.HANDLER);
    assert(!report.seen);

    assert(Report.from_keyfile_data("[Crash]\nPid=1\n") == null);
    assert(Report.from_keyfile_data("not a key file") == null);
    assert(Report.from_keyfile_data("[Other]\nPid=1\nExecutable=/bin/x\n") == null);
}

void test_block_escape() {
    string trace = "#0 main () at a.c:3\n#1 \\x start\n";
    assert(Report.unescape_block(Report.escape_block(trace)) == trace);
    assert(!Report.escape_block(trace).contains("\n"));
}

void test_seen_roundtrip() throws Error {
    string dir = DirUtils.make_tmp("crash-report-XXXXXX");
    string path = Path.build_filename(dir, "1-7.crash");
    FileUtils.set_contents(path, "[Crash]\nPid=7\nSignal=6\nTime=1\nExecutable=/bin/x\nCore=1-7.core\n");
    var report = Report.from_file(path);
    assert(report != null);
    report.backtrace = "#0 abort ()\n#1 main ()";
    report.backtrace_tool = "gdb";
    report.core_path = "";
    assert(report.mark_seen());
    var again = Report.from_file(path);
    assert(again.seen);
    assert(again.backtrace == "#0 abort ()\n#1 main ()");
    assert(again.backtrace_tool == "gdb");
    assert(again.core_path == "");
    FileUtils.remove(path);
    DirUtils.remove(dir);
}

void test_text_format() {
    var report = new Report();
    report.pid = 99;
    report.executable = "/usr/bin/files";
    report.app_name = "Files";
    report.app_id = "dev.sinty.Files";
    report.app_version = "1.2";
    report.signal_number = 11;
    report.os_name = "Example Linux 1";
    report.source = SourceKind.LAUNCHER;
    string text = report.to_text();
    assert(text.contains("App: Files\n"));
    assert(text.contains("Version: 1.2\n"));
    assert(text.contains("Signal: SIGSEGV (Segmentation fault)\n"));
    assert(text.contains("Collected By: App launcher\n"));
    assert(text.contains("Backtrace\nNot available"));
    assert(!text.contains("Command Line"));
    report.backtrace = "#0 crash ()";
    report.backtrace_tool = "eu-stack";
    assert(report.to_text().contains("Backtrace (eu-stack)\n#0 crash ()"));
    assert(report.display_name() == "Files");
}

void test_signals() {
    assert(Report.is_crash_signal(11));
    assert(Report.is_crash_signal(6));
    assert(!Report.is_crash_signal(15));
    assert(!Report.is_crash_signal(9));
    assert(Report.signal_label(6) == "SIGABRT (Aborted)");
    assert(Report.signal_label(0) == "");
}

void test_trim() {
    string raw = "[New LWP 12]\n[Thread debugging using libthread_db enabled]\n#0 a ()\n#1 b ()\n";
    assert(Report.trim_backtrace(raw) == "#0 a ()\n#1 b ()");
    var many = new StringBuilder();
    for (int i = 0; i < 20; i++) many.append("#%d f ()\n".printf(i));
    string gdb = "[New LWP 5]\nCore was generated by `x'.\nProgram terminated with signal SIGSEGV.\n#0 a ()\n\nThread 1 (LWP 5):\n#0 a ()\n#1 main ()\n";
    assert(Report.trim_backtrace(gdb) == "Thread 1 (LWP 5):\n#0 a ()\n#1 main ()");
    string cut = Report.trim_backtrace(many.str, 5);
    assert(cut.has_suffix("..."));
    assert(cut.split("\n").length == 6);
}

void test_coredumpctl() {
    string info = "           PID: 12 (crashy)\n        Signal: 11 (SEGV)\n\n"
        + "                Stack trace of thread 12:\n                #0  0x0000 crash (crashy + 0x10)\n"
        + "                #1  0x0000 main (crashy + 0x20)\n\n\n        ELF object binary architecture: AMD x86-64\n";
    string stack = Report.extract_coredumpctl_stack(info);
    assert(stack.has_prefix("Stack trace of thread 12:"));
    assert(stack.contains("\n  #1  0x0000 main"));
    assert(!stack.contains("ELF object"));
    assert(Report.extract_coredumpctl_stack("nothing") == "");

    string json = "[{\"time\":1790000000000000,\"pid\":10,\"uid\":1000,\"gid\":1000,\"sig\":11,"
        + "\"corefile\":\"present\",\"exe\":\"/usr/bin/crashy\",\"size\":1},"
        + "{\"time\":1790000001000000,\"pid\":11,\"uid\":0,\"gid\":0,\"sig\":6,"
        + "\"corefile\":\"missing\",\"exe\":\"/usr/sbin/daemon\",\"size\":null},"
        + "{\"time\":1700000000000000,\"pid\":9,\"uid\":1000,\"gid\":1000,\"sig\":6,"
        + "\"corefile\":\"present\",\"exe\":\"/usr/bin/old\",\"size\":1}]";
    var reports = SourceSelection.parse_coredumpctl_json(json, 1000, 1780000000000000);
    assert(reports.length == 1);
    assert(reports[0].pid == 10);
    assert(reports[0].timestamp == 1790000000);
    assert(reports[0].source == SourceKind.COREDUMPCTL);
    assert(reports[0].core_path == "coredumpctl:10");
    assert(SourceSelection.parse_coredumpctl_json("garbage", 1000, 0).length == 0);
    assert(SourceSelection.parse_coredumpctl_json("{}", 1000, 0).length == 0);
}

void test_selection() {
    var auto_all = SourceSelection.select("auto", true, true);
    assert(auto_all.length == 3);
    assert(auto_all[0] == SourceKind.HANDLER);
    assert(auto_all[1] == SourceKind.COREDUMPCTL);
    assert(auto_all[2] == SourceKind.LAUNCHER);
    var auto_none = SourceSelection.select("", false, false);
    assert(auto_none.length == 1 && auto_none[0] == SourceKind.LAUNCHER);
    var coredump_only = SourceSelection.select("auto", false, true);
    assert(coredump_only.length == 2 && coredump_only[0] == SourceKind.COREDUMPCTL);
    var explicit = SourceSelection.select("launcher, handler,bogus,handler", false, false);
    assert(explicit.length == 2);
    assert(explicit[0] == SourceKind.LAUNCHER);
    assert(explicit[1] == SourceKind.HANDLER);
    assert(SourceSelection.select("none", true, true).length == 0);

    assert(SourceSelection.pattern_uses_handler("|/usr/libexec/singularity-crash-handler %P %u %g %s %t %d %e"));
    assert(!SourceSelection.pattern_uses_handler("core"));
    assert(SourceSelection.pattern_uses_coredump("|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h"));
    assert(!SourceSelection.pattern_uses_coredump("/var/tmp/core.%e.%p"));
}

void test_config() {
    var config = new Config();
    assert(config.sources == "auto");
    assert(config.spool_dir == Config.DEFAULT_SPOOL);
    config.apply("[Crash Reporter]\nSources=handler,launcher\nSpoolDir=/srv/crash\nBacktraceTool=EU-STACK\n"
        + "BacktraceTimeout=9999\nNotifyUnknownPrograms=true\n[Handler]\nMinUid=1000\n");
    assert(config.sources == "handler,launcher");
    assert(config.spool_dir == "/srv/crash");
    assert(config.backtrace_tool == "eu-stack");
    assert(config.backtrace_timeout == 30);
    assert(config.notify_unknown);
    assert(config.user_spool_dir(1000) == "/srv/crash/1000");
    var untouched = new Config();
    untouched.apply("garbage");
    assert(untouched.sources == "auto");
}

void test_metadata() {
    string xml = "<component><url type=\"homepage\">https://example.org</url>"
        + "<url type=\"bugtracker\">https://example.org/issues?a=1&amp;b=2</url>"
        + "<releases><release version=\"3.1\" date=\"2026-01-01\"/><release version=\"3.0\"/></releases></component>";
    assert(AppMetadata.metainfo_version(xml) == "3.1");
    assert(AppMetadata.metainfo_bug_url(xml) == "https://example.org/issues?a=1&b=2");
    assert(AppMetadata.metainfo_bug_url("<url type=\"bugtracker\">javascript:alert(1)</url>") == "");
    assert(AppMetadata.sanitize_url("file:///etc/passwd") == "");
    assert(AppMetadata.sanitize_url(" https://x.org/bugs ") == "https://x.org/bugs");
    assert(AppMetadata.metainfo_version("<component/>") == "");
}

void test_rate_limit() {
    var limiter = new RateLimiter(600, 3, 60, 5);
    assert(limiter.check("a", 1000) == RateLimiter.Verdict.SHOW);
    assert(limiter.check("a", 1010) == RateLimiter.Verdict.SHOW);
    assert(limiter.check("a", 1020) == RateLimiter.Verdict.REPEATED);
    assert(limiter.check("a", 1030) == RateLimiter.Verdict.SUPPRESS);
    assert(limiter.check("a", 1700) == RateLimiter.Verdict.SHOW);
    var burst = new RateLimiter(600, 3, 60, 5);
    for (int i = 0; i < 5; i++) assert(burst.check("app%d".printf(i), 2000) == RateLimiter.Verdict.SHOW);
    assert(burst.check("app9", 2001) == RateLimiter.Verdict.SUPPRESS);
    assert(burst.check("app9", 2100) == RateLimiter.Verdict.SHOW);
}

void main() {
    test_report_parsing();
    test_block_escape();
    try {
        test_seen_roundtrip();
    } catch (Error e) {
        error(e.message);
    }
    test_text_format();
    test_signals();
    test_trim();
    test_coredumpctl();
    test_selection();
    test_config();
    test_metadata();
    test_rate_limit();
}
